import { formatRelativeTime } from '../lib/mailbox';
import Avatar from './Avatar';
import MailIcon from './MailIcon';

export default function ThreadRow({ thread, selected, unread, compact, selectedForBulk, onSelect, onToggleSelected, onStar, onQuickAction }) {
  const latest = thread[thread.length - 1];
  const inbound = [...thread].reverse().find((message) => message.direction === 'inbound') || latest;
  const preview = (latest?.text_body || latest?.subject || '').replace(/\s+/g, ' ').trim();
  const label = latest?.label || thread.find((message) => message.label)?.label || 'other';
  const address = inbound?.from_address || latest?.to_address || 'Unknown';
  return <div className="mail-thread-row" role="button" tabIndex={0} aria-selected={selected} data-unread={unread} data-density={compact ? 'compact' : 'comfortable'} onClick={() => onSelect(thread[0].thread_id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(thread[0].thread_id); } }}><input type="checkbox" checked={selectedForBulk} onClick={(event) => event.stopPropagation()} onChange={() => onToggleSelected(thread[0].thread_id)} aria-label={`Select ${latest?.subject || 'conversation'}`} /><Avatar address={address} /><div className="mail-thread-main"><div className="mail-thread-top">{unread && <span className="mail-unread-dot" />}<span className="mail-thread-sender">{address}</span><span className="mail-thread-time">{formatRelativeTime(latest?.received_at)}</span></div><div className="mail-thread-subject">{latest?.subject || '(no subject)'}</div><div className="mail-thread-preview">{preview || 'No message content'}</div><div className="mail-thread-bottom"><span className="mail-badge">{label}</span>{thread.length > 1 && <span className="mail-badge">{thread.length} messages</span>}{thread.some((message) => message.attachments?.length) && <span className="mail-badge"><MailIcon name="paperclip" size={12} /> attachment</span>}{latest?.claimed_by && <span className="mail-badge">{latest.claimed_by.slice(0, 2).toUpperCase()}</span>}</div></div><div className="mail-row-actions"><button className="mail-icon-button" type="button" onClick={(event) => { event.stopPropagation(); onStar(thread[0].thread_id, thread.some((message) => message.starred)); }} aria-label="Toggle star"><MailIcon name="star" size={16} /></button><button className="mail-icon-button" type="button" onClick={(event) => { event.stopPropagation(); onQuickAction('archive', thread[0].thread_id); }} aria-label="Archive thread"><MailIcon name="archive" size={16} /></button></div></div>;
}
